services:
  - type: web
    name: gymfit-backend
    env: node
    plan: free
    rootDir: backend
    autoDeploy: false
    buildCommand: npm install --include=dev && npm run build && npm prune --production
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: gymfit-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://gym-fit-sandy.vercel.app
      - key: BCRYPT_SALT_ROUNDS
        value: 10
      - key: NODE_VERSION
        value: 20
      - key: DB_SYNCHRONIZE
        value: "true"

databases:
  - name: gymfit-db
    plan: free
    databaseName: gymfit
    user: gymfit_user
