name: Deploy Backend to Render

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    #contenedor para la db
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: gymfit_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint and formatting check
        run: npm run lint

      - name: Run Tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_USERNAME: admin
          DB_PASSWORD: password123
          DB_NAME: gymfit_test
          NODE_ENV: test
          JWT_SECRET: change_me_dummy_secret_for_actions_runs_only
          JWT_EXPIRES_IN: 8h
          JWT_REFRESH_EXPIRATION: 7d
          CORS_ORIGIN: https://gym-fit-sandy.vercel.app
          BCRYPT_SALT_ROUNDS: 10
        run: |
          npm run test -- --passWithNoTests
          npm run test:e2e

      - name: Build Application
        run: npm run build

      - name: Trigger Render Deploy Hook
        if: success()
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
